services:
- type: web
  name: tdp-tutorial-blog-test-web
  env: static
  buildCommand: yarn && yarn rw build web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 14
  routes:
  - type: rewrite
    source: /.redwood/functions/*
    destination: https://tdp-tutorial-blog-test-api.onrender.com/*
  - type: rewrite
    source: /*
    destination: /index.html

- type: web
  name: tdp-tutorial-blog-test-api
  env: node
  buildCommand: yarn && yarn rw deploy render api
  startCommand: yarn rw serve api
  envVars:
  - key: NODE_VERSION
    value: 14
  - key: DATABASE_URL
    fromDatabase:
      name: tdp-tutorial-blog-test-db
      property: connectionString

databases:
  - name: tdp-tutorial-blog-test-db

