services:
- name: tdp-tutorial-blog-test-web
  type: web
  env: static
  buildCommand: yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 14
  routes:
  - type: rewrite
    source: /.redwood/functions/*
# replace destination api url after first deploy to Render
    destination: replace_me_with_api_url/*
  - type: rewrite
    source: /*
    destination: /index.html

- name: tdp-tutorial-blog-test-api
  type: web
  env: node
  buildCommand: yarn && yarn rw deploy render api
  startCommand: yarn rw serve api
  envVars:
  - key: NODE_VERSION
    value: 14
  - key: DATABASE_URL
    value: file:./data/sqlite.db
  disk:
    name: sqlite-data
    mountPath: /opt/render/project/src/api/db/data
    sizeGB: 1
